### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by solarisis** [ekscrypto/Base64#17]
can I use this to encode images? if yes how fast is this compared to default NSDATA base64 conversion?

**Comment by ekscrypto** [comment]
Yes you can use it to encode any type of NSData.  When last tested (see README file update time) this was faster than any and all other implementations I could put my hands on; that being said it was never ran against iOS 11 so they may have improved their stats. Should be a relatively safe bet to use even to this day; also ensures backward compatibility with older releases of iOS without losing any performance.  By the way, do let me know if you end up doing performance testing and have some results available for me; always curious to see how it fairs!
