### ISSUE TITLE
Decrypted NSData has an extra character at the end

### ISSUE THREAD

**Issue by marconealberto** [ekscrypto/Base64#19]
When decrypted, the NSData has often (not sure when exactly this happen) an extra character at the end, always a 7.
What am I doing wrong?

```
NSString *str = [[self convertToString:args] stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
NSData *decodedData = [self dataFromBase64String:paddedStr];
```

This is my code.

**Comment by ekscrypto** [comment]
Is your decoded string properly padded with '=' symbols at the end?  If improperly padded, there could be errors in decoding the last character.

**Comment by marconealberto** [comment]
great catch! we had the padded '=' symbol converted to %3D by the webservice.
Thank you very much!
