### ISSUE TITLE
Public Domain - Base64-1.1.2.zip

### ISSUE THREAD

**Issue by phaupt** [ekscrypto/Base64#20]
Dear Creator

Would it be okay to use your work [Base64-1.1.2.zip] under Creative Commons CC0 v1.0 Universal License (CC0 v1.0)? 

The Swiss law do not recognize a permanent relinquishment of Copyrights as the Public Domain provides for.

Thank you very much and kind regards
Philipp

**Comment by ekscrypto** [comment]
You have my authorization to use it under the Creative Commons CCO v1.0 Universal License (CCO v1.0) as requested.

--
Dave Poirier
skype: ekscrypto
twitter: @ekscrypto
facebook: /ekscrypto
email: ekscrypto@gmail.com

All I need is a towel, everything else can be answered by 42.

**Comment by phaupt** [comment]
Thank you, much appreciated!
