### ISSUE TITLE
Do you have a plan to add SPM support?

### ISSUE THREAD

**Issue by lolgear** [ekscrypto/Base64#22]
It would be nice if you add SPM support.

**Comment by ekscrypto** [comment]
I really do not see any benefit of using this library with Swift 5; it has built-in support for Base64 that is relatively fast.  I haven't run speed comparison but haven't had any issues yet in my projects with the built-in Base64 libraries.

**Comment by alvinchongry** [comment]
readme

**Comment by alvinchongry** [comment]
> It would be nice if you add SPM support.

**Comment by ekscrypto** [comment]
It is supported already
